import React, {useState, useEffect}  from 'react'
import Card from '@material-ui/core/Card'
import CardHeader from '@material-ui/core/CardHeader'
import CardMedia from '@material-ui/core/CardMedia'
import Typography from '@material-ui/core/Typography'
import Grid from '@material-ui/core/Grid'
import {makeStyles} from '@material-ui/core/styles'
import {read} from './api-auction.js'
import {Link} from 'react-router-dom'
import auth from '../auth/auth-helper'
import Timer from './Timer'
import Bidding from './Bidding'

